from pathlib import Path
import re

# Paths
md_file = Path(r"C:\Users\Administrator\.gemini\antigravity\brain\e493cad9-8d24-49b2-81b4-dda87f0ba2d8\technical_documentation.md")
html_file = Path(r"C:\Users\Administrator\.gemini\antigravity\brain\e493cad9-8d24-49b2-81b4-dda87f0ba2d8\technical_documentation.html")

# Read markdown
with open(md_file, 'r', encoding='utf-8') as f:
    md_content = f.read()

# Basic markdown to HTML conversion (simple approach)
html_body = md_content

# Convert headers
html_body = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html_body, flags=re.MULTILINE)
html_body = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html_body, flags=re.MULTILINE)
html_body = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html_body, flags=re.MULTILINE)
html_body = re.sub(r'^#### (.+)$', r'<h4>\1</h4>', html_body, flags=re.MULTILINE)

# Convert bold and italic
html_body = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_body)
html_body = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html_body)

# Convert inline code
html_body = re.sub(r'`([^`]+)`', r'<code>\1</code>', html_body)

# Convert code blocks
html_body = re.sub(r'```(\w+)?\n(.*?)```', r'<pre><code>\2</code></pre>', html_body, flags=re.DOTALL)

# Convert horizontal rules
html_body = html_body.replace('---', '<hr>')

# Convert line breaks
html_body = html_body.replace('\n\n', '</p><p>')
html_body = '<p>' + html_body + '</p>'

# Basic table conversion (simple tables only)
# This is a simplified approach - tables will need manual  formatting

# CSS styling
css_style = """
body {
    font-family: 'Segoe UI', Arial, sans-serif;
    line-height: 1.6;
    color: #333;
    max-width: 900px;
    margin: 0 auto;
    padding: 40px;
    background: white;
}
h1 {
    color: #472825;
    border-bottom: 3px solid #D3AB80;
    padding-bottom: 10px;
    margin-top: 40px;
}
h2 {
    color: #472825;
    border-bottom: 2px solid #96786F;
    padding-bottom: 8px;
    margin-top: 35px;
}
h3 {
    color: #96786F;
    margin-top: 25px;
}
h4 {
    color: #472825;
    margin-top: 20px;
}
table {
    border-collapse: collapse;
    width: 100%;
    margin: 20px 0;
    font-size: 14px;
}
th {
    background-color: #472825;
    color: white;
    padding: 12px;
    text-align: left;
    font-weight: bold;
}
td {
    border: 1px solid #ddd;
    padding: 10px;
    vertical-align: top;
}
tr:nth-child(even) {
    background-color: #FFF4E2;
}
code {
    background-color: #FDE4BC;
    padding: 2px 6px;
    border-radius: 3px;
    font-family: 'Consolas', 'Courier New', monospace;
    font-size: 13px;
}
pre {
    background-color: #FFF4E2;
    border-left: 4px solid #D3AB80;
    padding: 15px;
    overflow-x: auto;
    border-radius: 4px;
}
pre code {
    background-color: transparent;
    padding: 0;
}
blockquote {
    border-left: 4px solid #D3AB80;
    padding-left: 15px;
    color: #666;
    font-style: italic;
    margin: 20px 0;
}
hr {
    border: none;
    border-top: 2px solid #D3AB80;
    margin: 30px 0;
}
p {
    margin: 15px 0;
}
ul, ol {
    margin: 15px 0;
    padding-left: 30px;
}
li {
    margin: 8px 0;
}
strong {
    color: #472825;
}
a {
    color: #D3AB80;
    text-decoration: none;
}
a:hover {
    text-decoration: underline;
}
@media print {
    body {
        padding: 20px;
    }
    h1, h2, h3 {
        page-break-after: avoid;
    }
}
"""

# Wrap HTML with proper structure
full_html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Valley Hub - Technical Documentation</title>
    <style>{css_style}</style>
</head>
<body>
    <div class="markdown-body">
        {html_body}
    </div>
    <hr>
    <footer style="text-align: center; color: #96786F; font-size: 12px; margin-top: 40px;">
        <p>Generated by SandScript Team | New Valley Hub Project</p>
        <p>© 2026 New Valley Hub. Built for "New Valley Innovates" Hackathon</p>
    </footer>
</body>
</html>
"""

# Write HTML file
with open(html_file, 'w', encoding='utf-8') as f:
    f.write(full_html)

print(f"✅ HTML generated successfully!")
print(f"📄 Location: {html_file}")
print(f"\n📋 To convert to PDF:")
print(f"1. Open the HTML file in your browser (double-click it)")
print(f"2. Press Ctrl+P (Print)")
print(f"3. Select 'Save as PDF' or 'Microsoft Print to PDF' as the destination")
print(f"4. Adjust settings if needed (margins, scale, etc.)")
print(f"5. Click 'Save'")
print(f"\n✨ The document uses your brand colors and is print-optimized!")
