# Generated by Django 5.2.10 on 2026-01-25 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['parent__order', 'order', 'name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='service',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='service',
            name='is_24_hours',
            field=models.BooleanField(default=False, help_text='Open 24/7'),
        ),
        migrations.AddField(
            model_name='service',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Category description'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within parent'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure. Null = root category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text="Subcategory for this service (e.g., 'Hospitals' under 'Medical')", on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
