# Generated by Django 5.2.10 on 2026-01-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, help_text='URL to external image (HTTPS)', max_length=500),
        ),
    ]
