# Generated by Django 5.2.10 on 2026-01-25 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='locations/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attraction_type', models.CharField(choices=[('natural', 'Natural Reserve'), ('historical', 'Historical Site'), ('cultural', 'Cultural Center')], max_length=50)),
                ('visit_duration_minutes', models.PositiveIntegerField(help_text='Average time spent in minutes')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DigitalArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='artifacts/')),
                ('model_3d_file', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('virtual_tour_url', models.URLField(blank=True, help_text='Link to 360 view if hosted externally')),
                ('related_attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='tourism.attraction')),
            ],
        ),
    ]
