# Generated by Django 5.2.10 on 2026-01-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.URLField(blank=True, help_text='URL to external image (HTTPS)', max_length=500),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
