# Generated by Django 5.2.10 on 2026-01-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_governorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, help_text='Google Gemini API Key for AI chatbot. Leave blank to use environment variable.', max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
