# Generated by Django 6.0.2 on 2026-02-17 18:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_siteconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalartifact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Digital Artifact', 'verbose_name_plural': 'Digital Artifacts'},
        ),
        migrations.AddField(
            model_name='digitalartifact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalartifact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='digitalartifact',
            name='description',
            field=models.TextField(help_text='Detailed description of the artifact'),
        ),
        migrations.AlterField(
            model_name='digitalartifact',
            name='image',
            field=models.ImageField(blank=True, help_text='Poster/preview image for the artifact', null=True, upload_to='artifacts/images/'),
        ),
        migrations.AlterField(
            model_name='digitalartifact',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL for image (optional, falls back to uploaded image)'),
        ),
        migrations.AlterField(
            model_name='digitalartifact',
            name='model_3d_file',
            field=models.FileField(blank=True, help_text='Upload .glb for Android/Web or .usdz for iOS AR', null=True, upload_to='artifacts/models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'usdz'])]),
        ),
        migrations.AlterField(
            model_name='digitalartifact',
            name='name',
            field=models.CharField(help_text='Name of the artifact', max_length=255),
        ),
        migrations.AlterField(
            model_name='digitalartifact',
            name='related_attraction',
            field=models.ForeignKey(blank=True, help_text='Link to a physical attraction in New Valley', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='tourism.attraction'),
        ),
        migrations.AlterField(
            model_name='digitalartifact',
            name='virtual_tour_url',
            field=models.URLField(blank=True, help_text='Link to 360° view if hosted externally'),
        ),
    ]
