# Generated by Django 6.0.2 on 2026-02-17 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_alter_digitalartifact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SouvenirAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the asset', max_length=255)),
                ('category', models.CharField(choices=[('background', 'Background Image'), ('sticker', 'Sticker/Overlay'), ('frame', 'Photo Frame')], help_text='Type of souvenir asset', max_length=20)),
                ('image_file', models.ImageField(help_text='The actual image file (PNG with transparency for stickers/frames)', upload_to='souvenir/assets/')),
                ('is_premium', models.BooleanField(default=False, help_text='Mark as premium/featured asset')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Souvenir Asset',
                'verbose_name_plural': 'Souvenir Assets',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='digitalartifact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Digital Artifact (Legacy)', 'verbose_name_plural': 'Digital Artifacts (Legacy)'},
        ),
        migrations.CreateModel(
            name='MuseumArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the museum artifact', max_length=255)),
                ('description', models.TextField(help_text='Historical/cultural description of the artifact')),
                ('image', models.ImageField(help_text='Preview image/poster for the artifact', upload_to='museum/posters/')),
                ('model_3d_file', models.FileField(help_text='3D model file (.glb for Web/Android, .usdz for iOS)', upload_to='museum/models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'usdz'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_attraction', models.ForeignKey(blank=True, help_text='Physical location in New Valley where this artifact was found/displayed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='museum_artifacts', to='tourism.attraction')),
            ],
            options={
                'verbose_name': 'Museum Artifact',
                'verbose_name_plural': 'Museum Artifacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
