# Generated by Django 6.0.2 on 2026-02-17 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_museumartifact_image_url_souvenirasset_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museumartifact',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='souvenirasset',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='museumartifact',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Preview image/poster for the artifact', upload_to='museum/posters/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='souvenirasset',
            name='image_file',
            field=models.ImageField(default=django.utils.timezone.now, help_text='The actual image file (PNG with transparency for stickers/frames)', upload_to='souvenir/assets/'),
            preserve_default=False,
        ),
    ]
