# Generated by Django 6.0.2 on 2026-02-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_remove_museumartifact_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumartifact',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste external image link here (optional backup)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='souvenirasset',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste external image link here (optional backup)', max_length=500, null=True),
        ),
    ]
