# Generated by Django 6.0.2 on 2026-02-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_museumartifact_image_url_souvenirasset_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumartifact',
            name='image',
            field=models.ImageField(blank=True, help_text='Preview image/poster for the artifact', null=True, upload_to='museum/posters/'),
        ),
        migrations.AlterField(
            model_name='souvenirasset',
            name='image_file',
            field=models.ImageField(blank=True, help_text='The actual image file (PNG with transparency for stickers/frames)', null=True, upload_to='souvenir/assets/'),
        ),
    ]
