# Generated by Django 6.0.2 on 2026-02-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0014_alter_museumartifact_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='museumartifact',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Museum Artifact', 'verbose_name_plural': 'Museum Artifacts'},
        ),
        migrations.AddField(
            model_name='museumartifact',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
    ]
