# Generated by Django 6.0.2 on 2026-02-24 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0015_alter_museumartifact_options_museumartifact_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSouvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField(help_text='Base-64 PNG data-URL of the souvenir canvas')),
                ('caption', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_souvenirs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Souvenir',
                'verbose_name_plural': 'Saved Souvenirs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_mode', models.CharField(default='unknown', max_length=20)),
                ('total_co2', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('route_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Trip',
                'verbose_name_plural': 'Saved Trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
