# Generated by Django 6.0.2 on 2026-02-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0017_user_saved_trip_souvenir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedtrip',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavedSouvenir',
        ),
        migrations.DeleteModel(
            name='SavedTrip',
        ),
    ]
